#!/bin/bash

# Hotkey for xflock4 (e.g., Super+L)
gsettings set org.xfce.desktop.keybindings display-logout "['<Super>l']"

# Hotkey for nmcli networking on (e.g., Super+N)
gsettings set org.xfce.desktop.keybindings custom-keybindings "['<Super>n']"

# Hotkey for nmcli networking off (e.g., Super+M)
gsettings set org.xfce.desktop.keybindings custom-keybindings "['<Super>m']"

# Add custom keybindings
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>n/ name 'Network On'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>n/ command 'nmcli networking on'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>n/ binding '<Super>n'

gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>m/ name 'Network Off'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>m/ command 'nmcli networking off'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>m/ binding '<Super>m'

# Hotkey for xflock4 (e.g., Super+X)
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>x/ name 'Lock Screen'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>x/ command 'xflock4'
gsettings set org.xfce.desktop.keybindings.custom-keybindings:/org/xfce/desktop/keybindings/custom-keybindings/<Super>x/ binding '<Super>x'
