#!/bin/bash

echo "Setting up hotkeys..."

# Function to set a hotkey and check for errors
set_hotkey() {
    local key="$1"
    local command="$2"
    if xfconf-query -c xfce4-keyboard-shortcuts -p "/commands/custom/$key" -n -t string -s "$command"; then
        echo "Hotkey for $command set to $key."
    else
        echo "Failed to set hotkey for $command to $key." >&2
    fi
}

# Set hotkeys
set_hotkey "<Super>l" "xflock4"                     # Lock screen
set_hotkey "<Super>n" "nmcli networking on"         # Enable networking
set_hotkey "<Super>m" "nmcli networking off"        # Disable networking
set_hotkey "<Super>d" "xfwm4 --minimize-all"        # Minimize all windows

echo "Hotkeys have been set up successfully."
